#!/bin/sh
set -e
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c  ibus-vadan.public ibus-vadan.private
fi
# End automatically added section
